### ISSUE TITLE
Integrate with nixpkgs

### ISSUE THREAD

**Issue by turion** [apkgbot/package-index#20]
We're currently improving the Agda infrastructure on nixpkgs. In the long run, we want to be able to reliably build interdependent Agda libraries in a reproducible way with nix. Currently the sources and revisions/versions are hardcoded in nix. There is some discussion whether and how to incorporate `package-index` with `nixpkgs` here: https://github.com/NixOS/nixpkgs/pull/87903

**Comment by turion** [comment]
Integrating `package-index` with `nixpkgs` would also make #15, #16, and #17 quite easy.

**Comment by jonaprieto** [comment]
It sounds great. This package-index is inspired by https://github.com/JuliaRegistries/General.
That's one option. From where agda-pkg or other tools can get information.
